### PR TITLE
[MRG] added the summary agent

### PR DESCRIPTION
**Pull request by huangyz0918**
### **User description**
We need to update the Github integration function as well, I will do this in the same PR

___

### **PR Type**
enhancement

___

### **Description**
- Introduced a new `SummaryAgent` class in `mle/agents/summarizer.py` to summarize GitHub projects, including project information, structure, issues, and source code.
- Implemented a `summary` method to interact with a model and return project summaries in JSON format.
- Added comments in `mle/function/__init__.py` for a new GitHub integration function schema, preparing for future enhancements.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>summarizer.py</strong><dd><code>Added `SummaryAgent` class for GitHub project summarization</code></dd></summary>
<hr>

mle/agents/summarizer.py

<li>Introduced a new <code>SummaryAgent</code> class for summarizing GitHub projects.<br> <li> Implemented initialization with model, GitHub repository, and console.<br> <li> Added system prompt and JSON output format for project summarization.<br> <li> Developed a <code>summary</code> method to handle model queries and return <br>summaries.

</details>

  </td>
  <td><a href="https://github.com/MLSysOps/MLE-agent/pull/147/files#diff-98ad8ed051584070f7d7d36729c0ae0792a281ae776d8eb4ffd4efcf9e4fe2c1">+84/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>__init__.py</strong><dd><code>Added comments for GitHub integration function schema</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

mle/function/__init__.py

<li>Added comments for a new GitHub integration function schema.<br> <li> Prepared for potential future implementation of project structure <br>reading.

</details>

  </td>
  <td><a href="https://github.com/MLSysOps/MLE-agent/pull/147/files#diff-f2e6bc3dafd54d1b5469bee2a24eaa27b6aa80bb104ddf1189680b3efdbe9e68">+16/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by huangyz0918** [comment]
How to test this PR?

run this command under an MLE-Agent project:

```shell
mle start report
```

And you will be requiring to enter a GitHub repo name, please make sure you have set the github token before running:

```shell
export GITHUB_TOKEN=xxx
```

**Comment by HuaizhengZhang** [comment]
image


why does a public repo require a token to analyze?

**Review by HuaizhengZhang — COMMENTED** [review]
current workflow is weired

I need to `mle new` first and then I can call `mle start report` for a non-relevant github repo in that project

**Comment by HuaizhengZhang** [comment]
I prefer a `mle report`

1. if users run `mle report` under our project without any github links, we generate reports for that project locally.
2. if users run `mle report github-url`, we create a project called `mle-report-github-repo-name` and put report in that project

**Review by HuaizhengZhang — APPROVED** [review]
we can merge and then improve next PR

**Comment by leeeizhang** [comment]
> I prefer a `mle report`
> 
> 
> 
> 1. if users run `mle report` under our project without any github links, we generate reports for that project locally.
> 
> 2. if users run `mle report github-url`, we create a project called `mle-report-github-repo-name` and put report in that project

awesome!! i will refactor the report workflow today!

**Comment by huangyz0918** [comment]
> I prefer a `mle report`
> 
> 1. if users run `mle report` under our project without any github links, we generate reports for that project locally.
> 2. if users run `mle report github-url`, we create a project called `mle-report-github-repo-name` and put report in that project

Agreed, @leeeizhang please file a PR to fix this, thank you!

**Pull request merged**
