### PR TITLE
[MRG] Improve advisor agent with markdown output

### PR DESCRIPTION
**Pull request by huangyz0918**
### **PR Type**
Enhancement

___

### **Description**
- Added a new `report` mode to the `mle start` command in the CLI.
- Implemented the `report` function in `mle.workflow.report` to handle the new mode.
- Integrated user prompts for dataset information and requirements.
- Utilized `AdviseAgent` to generate and display suggestions in a report format.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>cli.py</strong><dd><code>Add report mode to CLI start function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

mle/cli.py

<li>Added a new mode <code>report</code> to the <code>start</code> function.<br> <li> Imported <code>report</code> from <code>mle.workflow</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/MLSysOps/MLE-agent/pull/132/files#diff-346b4a2c637c537f5bd5dfbc35d6dcc4b7ec9fb95722b368aa2eebd55dc162bd">+4/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>__init__.py</strong><dd><code>Import report function in workflow init</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

mle/workflow/__init__.py

- Imported `report` function from `mle.workflow.report`.

</details>

  </td>
  <td><a href="https://github.com/MLSysOps/MLE-agent/pull/132/files#diff-12fcbff3815bc8ed02c799f150d9eed07072049fb70a49074d3132c0b23b4a26">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>report.py</strong><dd><code>Implement report mode workflow</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

mle/workflow/report.py

<li>Created a new <code>report</code> function to handle the report mode workflow.<br> <li> Added functions to ask for data information and user requirements.<br> <li> Integrated <code>AdviseAgent</code> to generate suggestions in a report.<br>

</details>

  </td>
  <td><a href="https://github.com/MLSysOps/MLE-agent/pull/132/files#diff-647562765012a92e026a3b5281dd379532e4b9903e7657fc63dc2882633fe0e7">+70/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by leeeizhang** [comment]
Nice markdown appearance! LGTM, and github action can also give many suggestions. lol~

**Comment by HuaizhengZhang** [comment]
How to use this new agent?

**Comment by HuaizhengZhang** [comment]
any screenshots or command lines

**Review by HuaizhengZhang — COMMENTED** [review]
need some docs

**Comment by huangyz0918** [comment]
`mle start report`

**Comment by huangyz0918** [comment]
You can have a try, but this report agent is still working in progress (currently the same with the `advisor`), the PR is mainly to add the markdown generation function. I will updating the agent in the next PR

**Pull request merged**
