### PR TITLE
[MRG] the local web server to display the MLE suggestions

### LINKED ISSUE #169: Web application of MLE-Agent
- summary rendering

### PR DESCRIPTION
**Pull request by huangyz0918**
### **User description**
Closes #169 

The backend server can be started under the mle project by using `mle serve`. 
The web is placed outside the mle-agent SDK, and should be launched individually.

#### Before submitting this PR, please make sure you have:

- [x] confirmed all checks still pass OR confirm CI build passes.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in
  the [credit file](https://github.com/MLSysOps/MLE-agent/blob/main/.github/OPEN_SOURCE_LICENSES.md).

___

### **PR Type**
enhancement, dependencies

___

### **Description**
- Introduced a FastAPI server with a root endpoint and CORS middleware.
- Added a new CLI command `serve` to start the FastAPI server with configurable host and port.
- Updated `requirements.txt` to include `fastapi` and `uvicorn` dependencies.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>cli.py</strong><dd><code>Add CLI command to start FastAPI server</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

mle/cli.py

<li>Added import for <code>uvicorn</code> and <code>app</code> from <code>mle.server</code>.<br> <li> Introduced a new CLI command <code>serve</code> to start the FastAPI server.<br> <li> Configured server host and port options with default values.<br>

</details>

  </td>
  <td><a href="https://github.com/MLSysOps/MLE-agent/pull/177/files#diff-346b4a2c637c537f5bd5dfbc35d6dcc4b7ec9fb95722b368aa2eebd55dc162bd">+11/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>__init__.py</strong><dd><code>Initialize server module with app import</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

mle/server/__init__.py

- Initialized the server module by importing `app`.

</details>

  </td>
  <td><a href="https://github.com/MLSysOps/MLE-agent/pull/177/files#diff-c1d2c61ef6706d63f8abc1cf896c39e629c5c290606de5ce61b018c405951121">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>app.py</strong><dd><code>Implement FastAPI application with CORS middleware</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

mle/server/app.py

<li>Created a FastAPI application instance.<br> <li> Added CORS middleware to allow all origins and methods.<br> <li> Defined a root endpoint returning a welcome message.<br>

</details>

  </td>
  <td><a href="https://github.com/MLSysOps/MLE-agent/pull/177/files#diff-4f7432c6b6b116c959893d35f6aa6d73600e0efc3e5df33a6cbe1240515a8ef1">+22/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>requirements.txt</strong><dd><code>Add FastAPI and Uvicorn to dependencies</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

requirements.txt

- Added `fastapi` and `uvicorn` as dependencies.

</details>

  </td>
  <td><a href="https://github.com/MLSysOps/MLE-agent/pull/177/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by HuaizhengZhang — APPROVED** [review]
could you write down the how users use this feature?

**Comment by huangyz0918** [comment]
> could you write down the how users use this feature?

Yes, sure! I will update the document when this feature is well-tested

**Comment by HuaizhengZhang** [comment]
free to merge so we can test it

**Review by leeeizhang — APPROVED** [review]

**Comment by leeeizhang** [comment]
awesome! we can merge at first 👨🏻‍💻

**Pull request merged**
